### PR TITLE
Get pedantic about and enforce style

### PR DESCRIPTION
**Pull request by spladug**
Make pylint happy by either fixing various little nits or explicitly
disabling checks on a site-by-site basis. I've opted to boost the
programatically enforced line-length limit to 100 characters, but we
should still aim to stay <80 where possible.

This also adds a "make lint" which gets run during CI to ensure we stay
on our toes here.

:eyeglasses: @dellis23 @dwick

### CODE REVIEW

**Comment by dellis23** [comment]
🐟 Cool!  Always helpful to get it started earlier before too many violations get cemented in.

**Comment by spladug** [comment]
(i'll fix the ci error in the morning. looks like differing versions of stuff from local.)

**Comment by dwick** [comment]
🐟 🎉

**Comment by spladug** [comment]
7c6fcf7909d1aba38c67835ee9a776b0b1f1c5b1

**Pull request closed without merging**
