### PR TITLE
WeightedLottery should allow samples as long as the source list

### PR DESCRIPTION
**Pull request by ketralnis**
This is equivalent to a full weighted shuffle

👓  @spladug

### CODE REVIEW

**Comment by ketralnis** [comment]
Hrm yeah, and I'll be doing this on fairly large lists (~1k to ~25k). I probably need to approach a little differently

**Comment by spladug** [comment]
Could do this trick? https://github.com/python/cpython/blob/master/Lib/random.py#L304-L309

**Comment by spladug** [comment]
@ketralnis should this be closed out?

**Comment by ketralnis** [comment]
Yeah, I think it's a good idea to close. If people bump up against it they're probably going to have the same efficiency trouble with it I did so working transparently is probably worse

**Pull request closed without merging**
